from ctypes import *
import ctypes as ct
import dtwainapi

def initialize_pdf_text_element(dtwain_dll, state):

    # Create the PDF Text element
    elem = dtwain_dll.DTWAIN_CreatePDFTextElement()

    if not elem:
        state.pdf_text_element = None
        return False

    # initialize the PDF text element.  This is used to write text to any PDF pages generated by the scanner
    # when acquiring to a PDF file.  We will use default font of "Helvetica"

    # Set the height of the font
    dtwain_dll.DTWAIN_SetPDFTextElementFloat(elem,ct.c_double(25.0),0,dtwainapi.DTWAIN_PDFTEXTELEMENT_FONTHEIGHT)

    # Set the (x,y) position of the text.  Note we use PDF coordinate system, where the lower left and lower right 
    # is (0, 0).
    dtwain_dll.DTWAIN_SetPDFTextElementLong(elem,100,100,dtwainapi.DTWAIN_PDFTEXTELEMENT_POSITION)

    # Set the color of the text
    color = dtwain_dll.DTWAIN_MakeRGB(127, 127, 127) # grey
    dtwain_dll.DTWAIN_SetPDFTextElementLong(elem,color,0,dtwainapi.DTWAIN_PDFTEXTELEMENT_COLOR)

    # We want to display this on all the PDF pages.
    dtwain_dll.DTWAIN_SetPDFTextElementLong(elem,dtwainapi.DTWAIN_PDFTEXT_ALLPAGES,0,dtwainapi.DTWAIN_PDFTEXTELEMENT_DISPLAYFLAGS)

    state.pdf_text_element = elem
    return True
